name: "Setup Environment"
description: "Setting environment for the project"

inputs:
  task-version:
    description: "Task version"
    required: true
    default: "3.33.1"
  python-version:
    description: "Python version"
    required: true
    default: "3.12.1"
  poetry-version:
    description: "Poetry version"
    required: true
    default: "1.7.1"
  cookiecutter-version:
    description: "Cookiecutter version"
    required: true
    default: "2.4.0"

runs:
  using: "composite"
  steps:
    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        version: ${{ inputs.task-version }}

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: ${{ inputs.poetry-version }}

    - name: Install Cookiecutter
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install cookiecutter==${{ inputs.cookiecutter-version }}
