version: 3

silent: true

vars:
  ROOT_NENV: "../node_modules"
  PENV: ".venv"

  SOURCE_FOLDERS: "bin lib tests"
  TOML_FILES: "pyproject.toml poetry.toml"
  PYTHON_FILES:
    sh: find {{ "{{" }}.SOURCE_FOLDERS}} -name '*.py' | tr '\n' ' '

  DEFAULT_IMAGE_NAME: "{{cookiecutter.service_slug}}"

{%- if cookiecutter.with_ngrok == 'true' %}

env:
  NGROK_PORT: "8080"
{%- endif %}

tasks:
  _python:
    internal: true
    cmds:
      - "{{ "{{" }}.PENV}}/bin/python {{ "{{" }}.COMMAND}}"

  _pyright:
    internal: true
    cmds:
      - "{{ "{{" }}.ROOT_NENV}}/.bin/pyright {{ "{{" }}.COMMAND}}"

  _toml-sort:
    internal: true
    cmds:
      - "{{ "{{" }}.PENV}}/bin/toml-sort {{ "{{" }}.COMMAND}}"

  _sort_all:
    internal: true
    cmds:
      - cmd: "{{ "{{" }}.PENV}}/bin/sort-all {{ "{{" }}.COMMAND}}"

  _deptry:
    internal: true
    cmds:
      - "{{ "{{" }}.PENV}}/bin/deptry {{ "{{" }}.COMMAND}}"

  init:
    desc: Initialize environment
    cmds:
      - echo 'Installing python dependencies...'
      - poetry install
        --no-root
        --with dev

  lint:
    desc: Run lint checks
    cmds:
      - echo 'Running poetry checks...'
      - poetry check --lock

      - echo 'Running deptry checks...'
      - task: _deptry
        vars: { COMMAND: "." }

      - echo 'Running black checks...'
      - task: _python
        vars: { COMMAND: -m black --check . }

      - echo 'Running toml-sort checks...'
      - task: _toml-sort
        vars: { COMMAND: "--check {{ "{{" }}.TOML_FILES}}" }

      - echo 'Running sort-all checks...'
      - task: _sort_all
        vars: { COMMAND: "--check {{ "{{" }}.PYTHON_FILES}}" }
      - echo ''

      - echo 'Running ruff checks...'
      - task: _python
        vars: { COMMAND: "-m ruff check {{ "{{" }}.SOURCE_FOLDERS}}" }

      - echo 'Running pyright checks...'
      - task: _pyright

  lint-fix:
    desc: Fix lint issues
    cmds:
      - echo 'Running poetry fixes...'
      - poetry lock --no-update
      - poetry check

      - echo 'Running deptry checks...'
      - task: _deptry
        vars: { COMMAND: "." }

      - echo 'Running black fixes...'
      - task: _python
        vars: { COMMAND: -m black --safe . }

      - echo 'Running toml-sort fixes...'
      - task: _toml-sort
        vars: { COMMAND: "--in-place {{ "{{" }}.TOML_FILES}}" }

      - echo 'Running sort-all fixes...'
      - task: _sort_all
        vars: { COMMAND: "--no-error-on-fix {{ "{{" }}.PYTHON_FILES}}" }

      - echo 'Running ruff fixes...'
      - task: _python
        vars: { COMMAND: "-m ruff check --fix {{ "{{" }}.SOURCE_FOLDERS}}" }

      - echo 'Running pyright fixes...'
      - task: _pyright

  image-bake:
    cmds:
      - echo 'Building image {{ "{{" }}.TARGET}}...'
      - docker buildx bake {{ "{{" }}.TARGET}}

  image-run:
    desc: Run image in container
    requires:
      vars:
        - TARGET
    cmds:
      - echo 'Running image {{ "{{" }}.TARGET}} target...'
      - docker run
        --env-file <( env| cut -f1 -d= )
        {{ "{{" }}.DEFAULT_IMAGE_NAME}}:{{ "{{" }}.TARGET}}
{%- if cookiecutter.with_trivy == 'true' %}

  image-scan:
    desc: Scan image for vulnerabilities
    cmds:
      - echo 'Scanning image for vulnerabilities...'
      - trivy image
        --config trivy.yaml
        {{ "{{" }}.DEFAULT_IMAGE_NAME}}:{{ "{{" }}.TARGET}}
    vars:
      TARGET: '{{ "{{" }}.TARGET | default "runtime"}}'
{%- endif %}

  test:
    desc: Run tests
    cmds:
      - echo 'Running pytest...'
      - task: _python
        vars: { COMMAND: "-m pytest" }

  test-container:
    desc: Run tests in container
    cmds:
      - task: image-bake
        vars: { TARGET: tests_dev }
      - task: image-run
        vars: { TARGET: tests }

  test-coverage-run:
    desc: Run tests with coverage
    cmds:
      - echo 'Running test coverage...'
      - task: _python
        vars: { COMMAND: "-m coverage run -m pytest tests" }

  test-coverage-report:
    desc: Show test coverage report
    cmds:
      - echo 'Reporting test coverage...'
      - task: _python
        vars: { COMMAND: "-m coverage report -m" }

  test-coverage-html:
    desc: Show test coverage report in browser
    cmds:
      - echo 'Generating test coverage report...'
      - task: _python
        vars: { COMMAND: "-m coverage html" }
      - task: _python
        vars: { COMMAND: "-m webbrowser -t {{ "{{" }}.coverage_html}}" }
    vars:
      coverage_html:
        sh: "[ $(uname) = 'Darwin' ] && echo 'file://$(pwd)/htmlcov/index.html' || echo 'htmlcov/index.html'"

  clean:
    desc: Clean environment
    cmds:
      - echo 'Cleaning python dependencies...'
      - rm -rf {{ "{{" }}.PENV}}

      - echo 'Cleaning pytest cache...'
      - rm -rf .pytest_cache

      - echo 'Cleaning ruff cache...'
      - rm -rf .ruff_cache

      - echo 'Cleaning coverage results...'
      - rm -rf .coverage
      - rm -rf htmlcov

  dependencies-update:
    desc: Update python dependencies
    cmds:
      - echo 'Updating python dependencies...'
      - poetry update

  dependencies-check:
    desc: Check python dependencies
    cmds:
      - echo 'Checking python dependencies...'
      - poetry show --outdated

  dev-server-start:
    desc: Start development application
    cmds:
      - echo 'Starting server...'
      - task: _python
        vars: { COMMAND: "-m bin.main" }
{%- if cookiecutter.with_ngrok == 'true' %}

  dev-server-tunnel-start:
    desc: Start ngrok tunnel for development application
    cmds:
      - echo 'Setting up ngrok...'
      - ngrok config add-authtoken $NGROK_AUTH_TOKEN
      - echo 'Starting ngrok tunnel...'
      - ngrok http --domain=$NGROK_DOMAIN $NGROK_PORT
{%- endif %}

  dev-server-start-container:
    desc: Start development application in container
    cmds:
      - task: image-bake
        vars: { TARGET: runtime_dev }
      - task: image-run
        vars: { TARGET: runtime }

  update-from-template:
    desc: Update project from template
    cmds:
      - echo 'Updating project from template...'
      - cookiecutter
        --no-input
        --overwrite-if-exists
        --output-dir ../
        {{ "{{" }}.TEMPLATE_PATH}}
        service_name="{{cookiecutter.service_name}}"
        service_slug="{{cookiecutter.service_slug}}"
        service_short_slug="{{cookiecutter.service_short_slug}}"
        with_trivy="{{cookiecutter.with_trivy}}"
        with_ngrok="{{cookiecutter.with_ngrok}}"
        with_aiogram_utils="{{cookiecutter.with_aiogram_utils}}"
        with_aiohttp_utils="{{cookiecutter.with_aiohttp_utils}}"
        with_json_utils="{{cookiecutter.with_json_utils}}"
    vars:
      TEMPLATE_PATH: '{{ "{{" }}.TEMPLATE_PATH | default "https://github.com/ovsds/template-service-python"}}'

  ci-image-push:
    desc: Push image to registry for CI usage
    requires:
      vars:
        - IMAGE_TAG
        - IMAGE_REGISTRY
    cmds:
      - task: image-bake
        vars: { TARGET: runtime }

{%- if cookiecutter.with_trivy == 'true' %}

  ci-image-scan:
    desc: Scan image for vulnerabilities
    requires:
      vars:
        - IMAGE_TAG
        - IMAGE_REGISTRY
        - IMAGE_NAME
    cmds:
      - trivy image
        --config trivy.yaml
        {{ "{{" }}.IMAGE_REGISTRY}}/{{ "{{" }}.IMAGE_NAME}}:{{ "{{" }}.IMAGE_TAG}}
    env:
      TRIVY_DISABLE_VEX_NOTICE: "true"
{%- endif %}
