name: Check PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  check-pr:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Environment
        uses: ./.github/actions/setup_environment
        with:
          python-enabled: true
          poetry-enabled: true
          cookiecutter-enabled: true
          zizmor-enabled: true

      - name: Install Dependencies
        run: |
          task init

      - name: Lint PR
        run: |
          task lint
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for Zizmor

      - name: Test PR
        run: |
          task test
